### ISSUE TITLE
Have an Observable system to control state of cookies policy

### ISSUE THREAD

**Issue by AlbertoBasalo** [angularbuilders/angular-blueprint#23]
- [x] Have a generic observable store #24
- [x] Have an Angular service to control cookies policy #25
- [x] Have a command and a query for showPolicyDetails #26
- [x] Inject policyInfo on policy service #27
- [x] Simplify No policy container #28
